sbatch jobs/bul-ces.sh
sbatch jobs/bul-ces-fine.sh
sbatch jobs/bul-deu.sh
sbatch jobs/bul-deu-fine.sh
sbatch jobs/bul-fin.sh
sbatch jobs/bul-fin-fine.sh
sbatch jobs/bul-pes.sh
sbatch jobs/bul-pes-fine.sh
sbatch jobs/bul-slk.sh
sbatch jobs/bul-slk-fine.sh
sbatch jobs/bul-spa.sh
sbatch jobs/bul-spa-fine.sh
sbatch jobs/bul-tur.sh
sbatch jobs/bul-tur-fine.sh
sbatch jobs/ces-bul.sh
sbatch jobs/ces-bul-fine.sh
sbatch jobs/ces-deu.sh
sbatch jobs/ces-deu-fine.sh
sbatch jobs/ces-fin.sh
sbatch jobs/ces-fin-fine.sh
sbatch jobs/ces-pes.sh
sbatch jobs/ces-pes-fine.sh
sbatch jobs/ces-slk.sh
sbatch jobs/ces-slk-fine.sh
sbatch jobs/ces-spa.sh
sbatch jobs/ces-spa-fine.sh
sbatch jobs/ces-tur.sh
sbatch jobs/ces-tur-fine.sh
sbatch jobs/deu-bul.sh
sbatch jobs/deu-bul-fine.sh
sbatch jobs/deu-ces.sh
sbatch jobs/deu-ces-fine.sh
sbatch jobs/deu-fin.sh
sbatch jobs/deu-fin-fine.sh
sbatch jobs/deu-pes.sh
sbatch jobs/deu-pes-fine.sh
sbatch jobs/deu-slk.sh
sbatch jobs/deu-slk-fine.sh
sbatch jobs/deu-spa.sh
sbatch jobs/deu-spa-fine.sh
sbatch jobs/deu-tur.sh
sbatch jobs/deu-tur-fine.sh
sbatch jobs/fin-bul.sh
sbatch jobs/fin-bul-fine.sh
sbatch jobs/fin-ces.sh
sbatch jobs/fin-ces-fine.sh
sbatch jobs/fin-deu.sh
sbatch jobs/fin-deu-fine.sh
sbatch jobs/fin-pes.sh
sbatch jobs/fin-pes-fine.sh
sbatch jobs/fin-slk.sh
sbatch jobs/fin-slk-fine.sh
sbatch jobs/fin-spa.sh
sbatch jobs/fin-spa-fine.sh
sbatch jobs/fin-tur.sh
sbatch jobs/fin-tur-fine.sh
sbatch jobs/pes-bul.sh
sbatch jobs/pes-bul-fine.sh
sbatch jobs/pes-ces.sh
sbatch jobs/pes-ces-fine.sh
sbatch jobs/pes-deu.sh
sbatch jobs/pes-deu-fine.sh
sbatch jobs/pes-fin.sh
sbatch jobs/pes-fin-fine.sh
sbatch jobs/pes-slk.sh
sbatch jobs/pes-slk-fine.sh
sbatch jobs/pes-spa.sh
sbatch jobs/pes-spa-fine.sh
sbatch jobs/pes-tur.sh
sbatch jobs/pes-tur-fine.sh
sbatch jobs/slk-bul.sh
sbatch jobs/slk-bul-fine.sh
sbatch jobs/slk-ces.sh
sbatch jobs/slk-ces-fine.sh
sbatch jobs/slk-deu.sh
sbatch jobs/slk-deu-fine.sh
sbatch jobs/slk-fin.sh
sbatch jobs/slk-fin-fine.sh
sbatch jobs/slk-pes.sh
sbatch jobs/slk-pes-fine.sh
sbatch jobs/slk-spa.sh
sbatch jobs/slk-spa-fine.sh
sbatch jobs/slk-tur.sh
sbatch jobs/slk-tur-fine.sh
sbatch jobs/spa-bul.sh
sbatch jobs/spa-bul-fine.sh
sbatch jobs/spa-ces.sh
sbatch jobs/spa-ces-fine.sh
sbatch jobs/spa-deu.sh
sbatch jobs/spa-deu-fine.sh
sbatch jobs/spa-fin.sh
sbatch jobs/spa-fin-fine.sh
sbatch jobs/spa-pes.sh
sbatch jobs/spa-pes-fine.sh
sbatch jobs/spa-slk.sh
sbatch jobs/spa-slk-fine.sh
sbatch jobs/spa-tur.sh
sbatch jobs/spa-tur-fine.sh
sbatch jobs/tur-bul.sh
sbatch jobs/tur-bul-fine.sh
sbatch jobs/tur-ces.sh
sbatch jobs/tur-ces-fine.sh
sbatch jobs/tur-deu.sh
sbatch jobs/tur-deu-fine.sh
sbatch jobs/tur-fin.sh
sbatch jobs/tur-fin-fine.sh
sbatch jobs/tur-pes.sh
sbatch jobs/tur-pes-fine.sh
sbatch jobs/tur-slk.sh
sbatch jobs/tur-slk-fine.sh
sbatch jobs/tur-spa.sh
sbatch jobs/tur-spa-fine.sh
